services:
  api:
    build: .
    container_name: hotels-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/workspace
    command: npm run dev

  redis:
    image: redis:7-alpine
    container_name: hotels-redis
    ports:
      - "6379:6379"
